spring.application.name=movies

#  ------------------------ CONEXION A LA BD ------------------------------------#
#                       Documentación Oficial: spring.io/guides/gs/accessing-data-mysql
# ==>
#--Conección a la BD :
spring.datasource.url=jdbc:mysql://localhost:3306/movies
#--Credenciales en la BD:
spring.datasource.username=root
spring.datasource.password=MySQL@MyPassword
#--Para modificación de la Estructura de la BD sería:
#       por defecto sería la opción 'none', pero se pondrá en update para permitir modificar
spring.jpa.hibernate.dll-auto=update
#--Driver con el que se trabaja:
#       útil para cuando trabajamos con VARIOS drivers
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver